-- =============================================================
-- Brand B: Raw Orders Schema
-- Source system: SAP ERP → Oracle DB (on-premises)
--               Nightly batch export → SFTP → GCS → BigQuery
-- Customer identity: customer_uuid (UUID STRING) — SAP-generated
-- Load pattern: Nightly batch at 02:00 local time (one day lag)
-- Notes: Stores gross + net separately (pre/post-tax amounts).
--        No channel split — all transactions assumed in-store
--        (Brand B is purely brick-and-mortar).
--        txn_date is a DATE (not TIMESTAMP) — time granularity lost.
-- =============================================================

-- BigQuery DDL (raw ingestion layer — append only)
CREATE TABLE IF NOT EXISTS `{PROJECT_ID}.raw_brand_b.orders` (
  ord_number       STRING    NOT NULL,  -- SAP sales order number (e.g. "0000183940")
  customer_uuid    STRING    NOT NULL,  -- SAP customer UUID — globally unique within Brand B
  sku              STRING    NOT NULL,  -- SAP material number (e.g. "MAT-B-00348")
  location_code    STRING    NOT NULL,  -- SAP plant/store code (e.g. "PLANT-07")
  txn_date         DATE      NOT NULL,  -- Transaction DATE only — no time component
  gross_amount     NUMERIC   NOT NULL,  -- Pre-tax order value (local currency)
  net_amount       NUMERIC   NOT NULL,  -- Post-tax order value (local currency)
  currency_code    STRING    NOT NULL,  -- ISO 4217 (e.g. 'USD', 'CAD')
  _batch_date      DATE,                -- Nightly batch run date (pipeline metadata)
  _source_file     STRING               -- GCS SFTP drop file path
)
PARTITION BY txn_date
CLUSTER BY location_code
OPTIONS (
  description = "Brand B raw orders — SAP nightly batch export. Partition by txn_date, cluster by location_code (store). No time component available — date only."
);

-- =============================================================
-- Sample rows (illustrative — generated by ingest_batch.py)
-- =============================================================
/*
ord_number    | customer_uuid                        | sku         | location_code | txn_date   | gross_amount | net_amount | currency_code
0000183940    | 3f2504e0-4f89-11d3-9a0c-0305e82c3301 | MAT-B-00348 | PLANT-07      | 2024-03-15 | 109.99       | 97.89      | USD
0000183941    | a1b2c3d4-1234-5678-abcd-ef0123456789 | MAT-B-00901 | PLANT-02      | 2024-03-15 | 249.00       | 221.61     | USD
0000183942    | 3f2504e0-4f89-11d3-9a0c-0305e82c3301 | MAT-B-00112 | PLANT-07      | 2024-03-16 | 34.99        | 31.14      | USD
*/

-- =============================================================
-- Key schema pain points (for presentation talking points):
--   1. customer_uuid is a UUID — incompatible with Brand A integer, Brand C loyalty string
--   2. Date-only granularity (no timestamp) — cannot correlate with Brand A/C event times
--   3. Gross vs. net distinction — must choose one canonical "amount" field
--   4. Currency code present (multi-currency) — Brand A assumes USD only
--   5. Source is on-prem Oracle → nightly batch → no real-time option without CDC (debezium)
--   6. SAP material numbers (sku) don't map to Brand A/C SKUs — separate product resolution needed
-- =============================================================
