-- =============================================================
-- Brand C: Raw Orders Schema
-- Source system: Shopify + LoyaltyLion loyalty program
--               Shopify webhook → GCS event stream → BigQuery
-- Customer identity: loyalty_number (STRING) — LoyaltyLion ID
--                    (NOT all customers have one — guest checkouts
--                    have NULL loyalty_number)
-- Load pattern: Near-real-time webhook (Shopify order.created event)
-- Notes: Multi-currency Shopify store. Prices in subtotal_price
--        (excludes shipping). SKU is Shopify variant_id (integer).
-- =============================================================

-- BigQuery DDL (raw ingestion layer — append only)
CREATE TABLE IF NOT EXISTS `{PROJECT_ID}.raw_brand_c.orders` (
  transaction_id   STRING    NOT NULL,  -- Shopify order ID (e.g. "5678901234")
  loyalty_number   STRING,              -- LoyaltyLion ID (NULL for guest checkouts ~30%)
  variant_id       STRING    NOT NULL,  -- Shopify product variant ID (e.g. "VARIANT-C-445")
  shop_id          STRING    NOT NULL,  -- Shopify store ID (multi-store setup)
  created_at       TIMESTAMP NOT NULL,  -- Shopify order created_at (UTC)
  subtotal_price   NUMERIC   NOT NULL,  -- Order subtotal excluding shipping/tax in native currency
  currency         STRING    NOT NULL,  -- ISO 4217 currency (e.g. 'USD', 'GBP', 'AUD')
  fulfillment_status STRING,            -- 'fulfilled' | 'partial' | NULL (unfulfilled)
  _webhook_ts      TIMESTAMP,           -- When webhook was received (pipeline metadata)
  _source_topic    STRING               -- Pub/Sub topic this event came from
)
PARTITION BY DATE(created_at)
CLUSTER BY shop_id, currency
OPTIONS (
  description = "Brand C raw orders — Shopify webhook events. Partition by order date, cluster by shop_id and currency. loyalty_number is NULL for ~30% guest checkouts."
);

-- =============================================================
-- Sample rows (illustrative — generated by ingest_batch.py)
-- =============================================================
/*
transaction_id | loyalty_number | variant_id     | shop_id    | created_at               | subtotal_price | currency | fulfillment_status
5678901234     | LYL_888        | VARIANT-C-445  | SHOP-C-US  | 2024-03-15 14:30:00 UTC  | 79.99          | USD      | fulfilled
5678901235     | NULL           | VARIANT-C-112  | SHOP-C-UK  | 2024-03-15 14:45:00 UTC  | 55.00          | GBP      | NULL
5678901236     | LYL_888        | VARIANT-C-901  | SHOP-C-US  | 2024-03-16 09:00:00 UTC  | 120.00         | USD      | fulfilled
*/

-- =============================================================
-- Key schema pain points (for presentation talking points):
--   1. loyalty_number is NULL for ~30% of customers (guest checkout)
--      → These customers exist in Brand C but cannot be identified cross-brand
--      → Strategy: enrich with email match in Phase 2 (probabilistic identity)
--   2. variant_id is Shopify-specific — no global product master alignment with A/B
--   3. Multi-currency — requires FX normalization before any cross-brand revenue analysis
--   4. subtotal_price EXCLUDES shipping and tax (Brand A includes tax in amount_usd)
--   5. Real-time webhook model conflicts with Brand B's nightly batch — need temporal alignment
-- =============================================================
