-- =============================================================
-- Brand A: Raw Orders Schema
-- Source system: AWS Kinesis → S3 → Redshift (pre-migration)
-- Customer identity: cust_id (INTEGER) — internal legacy ID
-- Load pattern: Micro-batch every 15 min from Kinesis consumer
-- Notes: PHYSICAL/DIGITAL channel split; discount_pct stored
--        as decimal (0.10 = 10%). Timestamps in UTC.
-- =============================================================

-- BigQuery DDL (raw ingestion layer — append only)
CREATE TABLE IF NOT EXISTS `{PROJECT_ID}.raw_brand_a.orders` (
  order_id        STRING    NOT NULL,   -- Brand A internal order ref (e.g. "A-2024-00183")
  cust_id         INT64     NOT NULL,   -- Legacy integer customer ID — NOT globally unique
  product_id      STRING    NOT NULL,   -- Brand A SKU (e.g. "SKU-A-7734")
  store_id        STRING,               -- Physical store code OR NULL for online
  transaction_ts  TIMESTAMP NOT NULL,   -- UTC event timestamp
  amount_usd      NUMERIC   NOT NULL,   -- Gross order value in USD
  discount_pct    FLOAT64,              -- Discount fraction applied (0.0–1.0)
  channel         STRING    NOT NULL,   -- 'PHYSICAL' | 'DIGITAL'
  _ingestion_ts   TIMESTAMP,            -- When this row landed in BQ (pipeline metadata)
  _source_file    STRING                -- GCS file path this row came from
)
PARTITION BY DATE(transaction_ts)
CLUSTER BY channel, store_id
OPTIONS (
  description = "Brand A raw orders — partitioned by transaction date, clustered by channel and store_id for typical filter patterns"
);

-- =============================================================
-- Sample rows (illustrative — generated by ingest_batch.py)
-- =============================================================
/*
order_id       | cust_id | product_id  | store_id | transaction_ts           | amount_usd | discount_pct | channel
A-2024-001001  | 101     | SKU-A-7734  | STR-A-05 | 2024-03-15 10:22:14 UTC  | 89.99      | 0.10         | PHYSICAL
A-2024-001002  | 202     | SKU-A-1121  | NULL     | 2024-03-15 11:00:00 UTC  | 149.50     | 0.00         | DIGITAL
A-2024-001003  | 101     | SKU-A-5511  | NULL     | 2024-03-16 09:15:30 UTC  | 55.00      | 0.15         | DIGITAL
*/

-- =============================================================
-- Key schema pain points (for presentation talking points):
--   1. cust_id is an INTEGER — cannot join directly to Brand B (UUID) or C (string)
--   2. channel enum is Brand A proprietary — not shared with Brand B/C
--   3. discount stored as fraction, NOT absolute amount
--   4. No product category — requires join to Brand A product catalog table
-- =============================================================
